### ISSUE TITLE
Problem running autossh

### ISSUE THREAD

**Issue by comanche** [jazzl0ver/autossh#2]
I'm running `autossh` with the following command for MySQL:

``` bash
autossh -M 0 -L 3306:127.0.0.1:3306 -N -o ServerAliveInterval=60 <user>@<host>
```

It returns immediately without any error messages.  However I cannot connect with MySQL.  If I try the same command on a Linux box, it works fine.

Running the following with `ssh` works fine for MySQL:

``` bash
ssh -L 3306:127.0.0.1:3306 -N -o ServerAliveInterval=60 <user>@<host>
```

Is there's something I'm missing?

Thanks
:smile:

**Comment by jazzl0ver** [comment]
I have no ideas, sorry. You'd better ask the author
