### ISSUE TITLE
Any plans for 1.4g?

### ISSUE THREAD

**Issue by jpluimers** [jazzl0ver/autossh#3]
Hi,

1.4e has been a while ago, and 1.4g has been out since early this year: https://fossies.org/linux/privat/autossh-1.4g.tgz/

Any plans for a Windows binary of it?

Thanks for considering,

--jeroen

**Comment by jazzl0ver** [comment]
I don't use it anymore, but can try to build a binary for you later today

**Comment by jazzl0ver** [comment]
Done: https://github.com/jazzl0ver/autossh/releases/tag/1.4g

**Comment by jpluimers** [comment]
Thanks!
