### ISSUE TITLE
No source code in release assets

### ISSUE THREAD

**Issue by gsmitheidw** [jazzl0ver/autossh#5]
No source code in-line or in the released assets. Neither the zip nor tar.gz contain any information or useful source material.
No information about how to compile - included dll package - no information on what it contains or where it came from.

**Comment by jazzl0ver** [comment]
You may grab the source code on the offsite mentioned in the README.md. Compilation was made under msys2 (https://www.msys2.org/) environment with these simple commands:
```
cd autossh-1.4g/
./configure
make
```
The supplied dll is a part of msys2.

Is there anything else I can assist you with?

**Comment by gsmitheidw** [comment]
That's great and explains much better, I couldn't find the mysys2 part mentioned in the any of the Readme.md files - thanks for clarifying!
