### ISSUE TITLE
it doesn't work properly as a service on Windows 10

### ISSUE THREAD

**Issue by dannyboodmann** [jazzl0ver/autossh#6]
Hello,

the program works fine if launched as a normal executable, but if I try to set it up as a service in Windows, it doesn't work properly.
To be specific, if I start the service, autossh starts, spins up another instance of itself, then starts the ssh; the issue is that the Windows service crashes. The result is a weird situation where the processes are running while the service looks like as stopped.

This happens no matter how the service has been created: manually, with NSSM, etc...

I know this isn't an issue with autossh but more the behaviour in a specific context, but it'd be nice to use autossh as a Windows service.

thanks for your help

**Comment by dannyboodmann** [comment]
Another quite important info: the variable AUTOSSH_NTSERVICE is set to "yes"

**Comment by jazzl0ver** [comment]
I'm sorry, I can't help you with that
